#!/usr/bin/env python3

# Copyright 2017 Hannes Ovrén
#
# This file is part of vsearch.
#
# vsearch is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# vsearch is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with vsearch.  If not, see <http://www.gnu.org/licenses/>.

import argparse
import os
import multiprocessing

import cv2
import tqdm

from vsearch.utils import load_descriptors_and_keypoints, FEATURE_TYPES, find_images, save_keypoints_and_descriptors
from vsearch.colornames import cname_file_for_image, calculate_colornames
from vsearch.sift import sift_file_for_image

SIFT = FEATURE_TYPES['sift']
CNAME = FEATURE_TYPES['colornames']


def worker(image_path):
    cname_file = cname_file_for_image(image_path)
    sift_file = sift_file_for_image(image_path)

    try:
        sift_des, keypoints = load_descriptors_and_keypoints(sift_file, descriptors=False)
    except IOError:
        keypoints = None

    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    descriptors, keypoints = calculate_colornames(image, keypoints=keypoints)

    save_keypoints_and_descriptors(cname_file, keypoints, descriptors)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.description = """Compute colornames descriptors for images in a directory"""
    parser.add_argument('directory', help='directory with images')
    args = parser.parse_args()

    directory = os.path.expanduser(args.directory)
    missing = []
    for f in find_images(directory):
        if not os.path.exists(cname_file_for_image(f)):
            missing.append(f)

    print('{:d} files in {} is missing colornames descriptors'.format(len(missing), directory))

    with multiprocessing.Pool() as pool, tqdm.tqdm(total=len(missing)) as pbar:
        for _ in pool.imap_unordered(worker, missing):
            pbar.update(1)
